version: "3"
services:
  shiny-app:
    container_name: bioMnorm
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8002:3838
    network_mode: bridge
    restart: always



